# Generated by Django 3.0.8 on 2020-09-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='', upload_to='students/images'),
        ),
    ]
